server:
  port: 8080

spring:

  data:
    elasticsearch:
      cluster-nodes: localhost:9200
      cluster-name: docker-cluster

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/processador-csv
    username: postgres
    password: 1y5h8j
    initialization-mode: always
    initialize: true
    continue-on-error: true
    platform: postgresql

  jpa:
    hibernate:
      ddl-auto: create
      format_sql: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        jdbc:
          lob.non_contextual_creation: true

oauth2-credentials:
  processador-csv:
    client: processador-csv-client
    secret: processador-csv-secret
