server:
  port: 8080

app-config:
  nome: Processador de CSV
  descricao: API REST do projeto Processasdor de CSV utilizando Spring Batch, PostgreSQL, ElasticSerach e Docker
  versao: 1.0.0
  url: localhost:${server.port}
  job:
    scheduler:
      every-hour: 0 0 */1 * * *

spring:

  batch:
    initialize-schema: never
    job:
      enabled: false

  data:
    elasticsearch:
     cluster-nodes: ${ELASTICSEARCH_CLUSTER_NODES}
     cluster-name: ${ELASTICSEARCH_CLUSTER_NAME}

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    initialization-mode: always
    initialize: true
    continue-on-error: true
    platform: postgresql

  jpa:
    hibernate:
      ddl-auto: create-drop
      format_sql: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        jdbc:
          lob.non_contextual_creation: true

oauth2-credentials:
  processador-csv:
    client: processador-csv-client
    secret: processador-csv-secret
