INSERT INTO PERMISSAO (ID, DESCRICAO, ROLE) VALUES (1, 'Administrador', 'ADMIN');
INSERT INTO PERMISSAO (ID, DESCRICAO, ROLE) VALUES (2, 'Usuário visitante', 'USER');

-- Senha descriptografada: 123456
INSERT INTO USUARIO (ID, NOME, EMAIL, SENHA) VALUES (1, 'USUÁRIO EXEMPLO', 'USUARIO@GMAIL.COM', '$2a$10$O6ncja0irwVs2UDsi4E1vO.4vEJ5WgCJIYOoowTlLVCE58JIOHudS');

INSERT INTO USUARIO_PERMISSAO (FK_USUARIO, FK_PERMISSAO) VALUES (1, 1);
INSERT INTO USUARIO_PERMISSAO (FK_USUARIO, FK_PERMISSAO) VALUES (1, 2);